# AWS CodeBuild BuildSpec
#
# build and test

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10.x
    commands:
      # Install dependencies needed for running tests
      - npm --version
      - npm ci

      # Prevent files from having a timestamp before 1980
      - find ./node_modules -mtime +10950 -exec touch {} \;

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade pip
      - pip install --upgrade awscli

  build:
    commands:
      - npm run build
      - aws cloudformation package --template template.yaml --s3-bucket $S3_BUCKET --output-template template-export.yaml
artifacts:
  type: zip
  files:
    - template-export.yaml
